### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '.\\data\\nuscenes\\nuscenes\\v1.0-trainval\\category.json'

### ISSUE THREAD

**Issue by CodingNoobMaster** [GANWANSHUI/GaussianOcc#11]
After running python tools/export_gt_depth_nusc.py cmd line in Windows, I got the above error. I've only downloaded the nuScenes v1.0 full dataset part 1. I couldn't manage to find the catergory.json file in the compressed file. Am I missing something or do I need the enitre dataset to run this cmd line. Here is the entire error.

``(gsocc) C:\Users\User\Desktop\GaussianOcc>python tools/export_gt_depth_nusc.py
Traceback (most recent call last):
  File "C:\Users\User\Desktop\GaussianOcc\tools\export_gt_depth_nusc.py", line 152, in <module>
    model = DepthGenerator('val')
  File "C:\Users\User\Desktop\GaussianOcc\tools\export_gt_depth_nusc.py", line 17, in __init__
    self.nusc = NuScenes(version=version,
  File "C:\Users\User\anaconda3\envs\gsocc\lib\site-packages\nuscenes\nuscenes.py", line 69, in __init__
    self.category = self.__load_table__('category')
  File "C:\Users\User\anaconda3\envs\gsocc\lib\site-packages\nuscenes\nuscenes.py", line 136, in __load_table__
    with open(osp.join(self.table_root, '{}.json'.format(table_name))) as f:
FileNotFoundError: [Errno 2] No such file or directory: '.\\data\\nuscenes\\nuscenes\\v1.0-trainval\\category.json``

**Comment by GANWANSHUI** [comment]
I guess you need to download the entire dataset
