### ISSUE TITLE
Error training looking for depth file

### ISSUE THREAD

**Issue by seamie6** [GANWANSHUI/GaussianOcc#28]
I am getting the following error attempting to train. It is looking for this file n008-2018-08-31-11-19-57-0400__CAM_FRONT__1535728806862404.npy but this sample is a training sample and we only generate it for validation so why is it searching for it?

```
(gsocc_new) X@X:~/GaussianOcc$ sh run_gs_occ.sh
/home/seamie/anaconda3/envs/gsocc_new/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
/home/seamie/anaconda3/envs/gsocc_new/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
---------------------------------------------------------
-------------log path: logs/nusc-sem-gs_all/seg_True_0.02_0.1_0.1_pose_yes_yes_mask_False/type_3dgs_0.0_s_0.2_180_l_self_en_w_0.1_ep_12_f_False_infi_True_cont_True_depth_0.1_80.0_101/exp_2024_10_29_19_53_10
/home/seamie/GaussianOcc/utils/losses/cross_entropy_loss.py:240: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
N_samples: 424
Voxel size: 0.399998125017578
Training model named: nusc-sem-gs
There are 20096 training items and 6019 validation items

========== NEW EPOCH : 0==========
Training
self.epoch: 0, lr: [0.0001, 0.001, 0.0001, 0.0001]
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    trainer.train()
  File "/home/seamie/GaussianOcc/runner.py", line 419, in train
    self.run_epoch()
  File "/home/seamie/GaussianOcc/runner.py", line 864, in run_epoch
    for batch_idx, inputs in enumerate(self.train_loader):
  File "/home/seamie/anaconda3/envs/gsocc_new/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/seamie/anaconda3/envs/gsocc_new/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/seamie/anaconda3/envs/gsocc_new/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/seamie/anaconda3/envs/gsocc_new/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/seamie/anaconda3/envs/gsocc_new/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/seamie/anaconda3/envs/gsocc_new/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seamie/anaconda3/envs/gsocc_new/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seamie/GaussianOcc/datasets/mono_dataset.py", line 156, in __getitem__
    self.get_info(inputs, frame_index, do_flip)
  File "/home/seamie/GaussianOcc/datasets/nusc_dataset.py", line 309, in get_info
    depth = np.load(os.path.join(self.depth_path, cam_sample['filename'][:-4] + '.npy'))
  File "/home/seamie/anaconda3/envs/gsocc_new/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/nuscenes/nuscenes/depth_full/samples/CAM_FRONT/n008-2018-08-31-11-19-57-0400__CAM_FRONT__1535728806862404.npy'
```

**Comment by GANWANSHUI** [comment]
Maybe you can generate the training depth as well, or set if else to ignore the depth loader in the training phase.

**Comment by seamie6** [comment]
Added a simple check is_train and it works now, have not tried to fully train yet though
